import type { Metadata } from 'next';
import localFont from 'next/font/local';
import '../style/global.css';
import { auth } from '../firebase';
import { AuthProvider } from '../context/AuthContext';

export const wanted = localFont({
  src: [
    {
      path: '../../public/fonts/WantedSansVariable.woff2',
      weight: '400 1000',
    },
  ],
  display: 'swap',
  variable: '--font-wanted',
});

export const metadata: Metadata = {
  title: 'WEATHER CLOSET',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={`${wanted.variable}`}>
        <div>
          <h1 className='hide'>실패없는 기온별 옷차림 가이드 - Weather closet</h1>
          <AuthProvider>{children}</AuthProvider>
        </div>
      </body>
    </html>
  );
}
